### ISSUE TITLE
Generics with https://github.com/josharian/impl/releases/tag/v1.3.0(master) doesn't work

### ISSUE THREAD

**Issue by Solverj** [edolphin-ydf/goimpl.nvim#15]
How to reproduce:

1. MasonInstall or install by go install github.com/josharian/impl@latest (v1.3.0)
2. Create any generic interface
3. Implement the generic interface
4. Error stating that interface doesn't exist.

Fix for me personally: 

go install github.com/josharian/impl@v1.2.0

Fix that would be community-wise great:

1. Require [type] at end of interface you want to implement.

**Comment by Solverj** [comment]
Also remember to delete v1.3.0(linux)

`sudo rm -rf ~/go/pkg/mod/github.com/josharian/impl@v.1.3.0`

**Comment by edolphin-ydf** [comment]
As the docuemnt symbol returned by lsp doesn't contain the generic info, it's hard to make it possible.


```
{
    containerName = "github.com/edolphin-ydf/test",
    kind = 11,
    location = {
      range = {
        ["end"] = {
          character = 6,
          line = 14
        },
        start = {
          character = 5,
          line = 14
        }
      },
      uri = "file:///Users/edolphin/test/main.go"
    },
    name = "I"
  }
```
The symbol info above is returned by lsp and `I` is a generic interface defined as follows

```
type I[T any] interface {
	String() string
}
```

As you can see, there is generic info.

**Comment by edolphin-ydf** [comment]
fixed

**Comment by edolphin-ydf** [comment]
Fixed. Glad to hear your feedback.

**Comment by Solverj** [comment]
This works as expected, I'm happy about it returning E! Thanks for your work; really appreciate it.

**Comment by Solverj** [comment]
This works as expected, I'm happy about it returning E! Thanks for your work; really appreciate it.
