### ISSUE TITLE
Cannot get list of interfaces to implement.

### ISSUE THREAD

**Issue by orlovm** [edolphin-ydf/goimpl.nvim#5]
I've installed `goimpl.nvim` via vim-plug and registered it as `telelescope` extension.

When I try to use it with `lua require'telescope'.extensions.goimpl.goimpl{}`, I get this notification:
`[telescope.filter_symbols]: interface symbol(s) were not part of the query results`

I have neovim 0,7. And the latest versions of all dependencies listed in readme.
And gopls configured and working correctly.

Please, tell me what I'm doing wrong. Plugin looks very usefull!

**Comment by Cih2001** [comment]
Hey,

https://github.com/edolphin-ydf/goimpl.nvim/commit/f3d1109fbaa881e3c9ab8fb4326a414fc9ef01da not only didn't fix the issue, but also broke the extension for me. I had to revert it.

**Comment by edolphin-ydf** [comment]
please try the newest main branch.

**Comment by edolphin-ydf** [comment]
> 

tested with newest telescope

**Comment by Cih2001** [comment]
There are still problems with it. There are times when your symbol list is not empty, but does not contain any interfaces. If you enter a character like *q* in the search box, such a case will occur. My PR (https://github.com/edolphin-ydf/goimpl.nvim/pull/6) fixes this problem by manually filtering out interfaces rather than using `utils.filter_symbols`
![Screenshot from 2022-07-04 18-33-47](https://user-images.githubusercontent.com/15686693/177193597-11869a7f-5fc5-489f-b226-82ddf77b0bf0.png)

**Comment by edolphin-ydf** [comment]
Ok. I got you. And there is some conflict, let me fix it.

**Comment by edolphin-ydf** [comment]
Done

**Comment by edte** [comment]
I also encountered a similar problem, there are some interfaces that won't show up
![image](https://user-images.githubusercontent.com/50194671/177272639-e554cf93-d956-4d79-b419-f10125b2a80c.png)

Only a few interfaces are displayed
![image](https://user-images.githubusercontent.com/50194671/177272787-db4669a1-5e16-4655-85fe-8e093582af75.png)

Plugins are up to date

**Comment by edolphin-ydf** [comment]
> I also encountered a similar problem, there are some interfaces that won't show up ![image](https://user-images.githubusercontent.com/50194671/177272639-e554cf93-d956-4d79-b419-f10125b2a80c.png)
> 
> Only a few interfaces are displayed ![image](https://user-images.githubusercontent.com/50194671/177272787-db4669a1-5e16-4655-85fe-8e093582af75.png)
> 
> Plugins are up to date

Have no idea on this.
I'v test on two project, a simple test project And a large project.
In the simple test project, everything works fine.
But in the large project, i'v met the same issue with you.
After some debug, i found that the lsp returned with missing some interfaces. So it's maybe the lsp's issue.

**Comment by edolphin-ydf** [comment]
@edte I'v found a new way to get what you want. See this [document](https://github.com/golang/tools/blob/master/gopls/doc/features.md) 
use the `exact` feature in the query
Character | Usage | Match
-- | -- | --
' | 'abc | exact
^ | ^printf | exact prefix
$ | printf$ | exact suffix

eg: 
`'Reader`

**Comment by edte** [comment]
it's work fine,thanks
