### ISSUE TITLE
Fish Shell Compatibility

### ISSUE THREAD

**Issue by jay-babu** [edolphin-ydf/goimpl.nvim#9]
Hello,

I am trying to use this plugin. Seems very useful. My default shell is Fish. This plugin does not seem to work with it. I think I found the error. I believe specifying `bash` or the intended shell, this plugin would work perfectly fine.

https://github.com/edolphin-ydf/goimpl.nvim/blob/72612d556627c72cc48df2d242a7588a48e9715f/lua/telescope/_extensions/goimpl_builtin.lua#L124

**Comment by jay-babu** [comment]
or maybe I need this locally, https://github.com/josharian/impl. trying it now

**Comment by jay-babu** [comment]
yes, that was the issue. I think needing the tool should be in the readme

**Comment by edolphin-ydf** [comment]
Added the dependence in readme.
